// Configuration object for user data and main navigation
export const data = {
  // User profile information for display in UI
  user: {
    name: "shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },

  // Main navigation items for app routing
  navMain: [
    {
      // Home navigation option triggers history push and dispatch
      callback() {
        window.history.pushState(null, '', this.path)
        window.dispatchEvent(new PopStateEvent('popstate'))
      },
      id: '1',        
      label: 'Home',    
      path: '/dashboard'
    },
    {
      // Autogenerated menu group with sub-options
      callback() {
        // Push route change and notify router
        window.history.pushState(null, '', this.path)
        window.dispatchEvent(new PopStateEvent('popstate'))
      },
      id: '2',
      label: 'Autogenerated',
      path: '',
      subOptionList: [
        
        {
          // Each sub-option uses the same callback logic for navigation
          callback() {
            window.history.pushState(null, '', this.path)
            window.dispatchEvent(new PopStateEvent('popstate'))
          },
          id: '3',   // Assign sequential IDs starting at 3
          label: "Books", // Use title from navMain array
          path: "/books"     // Use URL from navMain array
        },
        
        {
          // Each sub-option uses the same callback logic for navigation
          callback() {
            window.history.pushState(null, '', this.path)
            window.dispatchEvent(new PopStateEvent('popstate'))
          },
          id: '4',   // Assign sequential IDs starting at 3
          label: "Users", // Use title from navMain array
          path: "/users"     // Use URL from navMain array
        },
        
        {
          // Each sub-option uses the same callback logic for navigation
          callback() {
            window.history.pushState(null, '', this.path)
            window.dispatchEvent(new PopStateEvent('popstate'))
          },
          id: '5',   // Assign sequential IDs starting at 3
          label: "Authors", // Use title from navMain array
          path: "/authors"     // Use URL from navMain array
        },
        
        {
          // Each sub-option uses the same callback logic for navigation
          callback() {
            window.history.pushState(null, '', this.path)
            window.dispatchEvent(new PopStateEvent('popstate'))
          },
          id: '6',   // Assign sequential IDs starting at 3
          label: "Editorials", // Use title from navMain array
          path: "/editorials"     // Use URL from navMain array
        },
        
        {
          // Each sub-option uses the same callback logic for navigation
          callback() {
            window.history.pushState(null, '', this.path)
            window.dispatchEvent(new PopStateEvent('popstate'))
          },
          id: '7',   // Assign sequential IDs starting at 3
          label: "Categories", // Use title from navMain array
          path: "/categories"     // Use URL from navMain array
        }
        
      ]
    }
  ],
}
